// 필라멘트 재질별 기본 출력 설정값 (일반적인 권장 범위의 중간값 기준)
// 실제 값은 필라멘트 제조사 스펙시트를 우선하고, 여기 값은 "출발점"으로만 사용하세요.
export const MATERIAL_PRESETS = {
  PLA: {
    label: 'PLA',
    nozzleTemp: [190, 220],
    nozzleDefault: 205,
    bedTemp: [40, 60],
    bedDefault: 55,
    fanPercent: 100,
    printSpeed: [40, 60],
    retractDistance: 4,
    retractSpeed: 40,
    needsDrying: false,
    dryingTemp: null,
    dryingHours: null,
    needsEnclosure: false,
    diameterOptions: [1.75, 2.85],
    notes: '초보자에게 가장 무난한 재질. 냉각팬을 강하게 켜야 디테일이 잘 삽니다.',
  },
  'PLA+': {
    label: 'PLA+ / PLA Pro',
    nozzleTemp: [200, 225],
    nozzleDefault: 210,
    bedTemp: [45, 60],
    bedDefault: 55,
    fanPercent: 100,
    printSpeed: [40, 60],
    retractDistance: 4,
    retractSpeed: 40,
    needsDrying: false,
    dryingTemp: null,
    dryingHours: null,
    needsEnclosure: false,
    diameterOptions: [1.75, 2.85],
    notes: 'PLA보다 층간 강도가 좋음. 온도를 PLA보다 5~10도 높게 잡으면 안정적입니다.',
  },
  PETG: {
    label: 'PETG',
    nozzleTemp: [230, 250],
    nozzleDefault: 240,
    bedTemp: [70, 80],
    bedDefault: 75,
    fanPercent: 40,
    printSpeed: [30, 50],
    retractDistance: 5,
    retractSpeed: 30,
    needsDrying: true,
    dryingTemp: 65,
    dryingHours: 5,
    needsEnclosure: false,
    diameterOptions: [1.75, 2.85],
    notes: '습기를 잘 먹는 재질(흡습성). 실을 잘 늘어뜨리므로(스트링잉) 리트랙션과 냉각팬 조절이 중요합니다.',
  },
  ABS: {
    label: 'ABS',
    nozzleTemp: [230, 250],
    nozzleDefault: 240,
    bedTemp: [90, 110],
    bedDefault: 100,
    fanPercent: 0,
    printSpeed: [30, 50],
    retractDistance: 4,
    retractSpeed: 40,
    needsDrying: true,
    dryingTemp: 85,
    dryingHours: 7,
    needsEnclosure: true,
    diameterOptions: [1.75, 2.85],
    notes: '냉각팬을 끄거나 최소로 하고, 밀폐형(엔클로저) 프린터 사용을 강력 권장합니다. 출력 중 냄새가 나므로 환기 필수.',
  },
  ASA: {
    label: 'ASA',
    nozzleTemp: [240, 260],
    nozzleDefault: 250,
    bedTemp: [90, 110],
    bedDefault: 100,
    fanPercent: 0,
    printSpeed: [30, 50],
    retractDistance: 4,
    retractSpeed: 40,
    needsDrying: true,
    dryingTemp: 85,
    dryingHours: 7,
    needsEnclosure: true,
    diameterOptions: [1.75, 2.85],
    notes: 'ABS와 유사하지만 자외선(UV)에 강해 야외용 부품에 적합. 엔클로저와 환기가 필요합니다.',
  },
  TPU: {
    label: 'TPU (연성)',
    nozzleTemp: [210, 240],
    nozzleDefault: 220,
    bedTemp: [30, 60],
    bedDefault: 45,
    fanPercent: 50,
    printSpeed: [15, 30],
    retractDistance: 2,
    retractSpeed: 20,
    needsDrying: true,
    dryingTemp: 60,
    dryingHours: 6,
    needsEnclosure: false,
    diameterOptions: [1.75, 2.85],
    notes: '무르고 유연해서 압출기 걸림(잼)이 잦습니다. 출력 속도를 크게 낮추고 리트랙션은 최소화하세요.',
  },
  Nylon: {
    label: 'Nylon (나일론)',
    nozzleTemp: [245, 260],
    nozzleDefault: 250,
    bedTemp: [70, 100],
    bedDefault: 90,
    fanPercent: 20,
    printSpeed: [30, 45],
    retractDistance: 4,
    retractSpeed: 30,
    needsDrying: true,
    dryingTemp: 80,
    dryingHours: 10,
    needsEnclosure: true,
    diameterOptions: [1.75, 2.85],
    notes: '흡습성이 매우 강한 재질입니다. 반드시 완전 건조 후 출력하고, 가능하면 건조 상태를 유지하는 필라멘트 드라이박스를 사용하세요.',
  },
  PC: {
    label: 'PC (폴리카보네이트)',
    nozzleTemp: [270, 310],
    nozzleDefault: 290,
    bedTemp: [100, 130],
    bedDefault: 115,
    fanPercent: 0,
    printSpeed: [20, 40],
    retractDistance: 4,
    retractSpeed: 30,
    needsDrying: true,
    dryingTemp: 90,
    dryingHours: 8,
    needsEnclosure: true,
    diameterOptions: [1.75, 2.85],
    notes: '고온 출력이 필요한 고강도 재질. 고온 노즐/베드를 지원하는 프린터인지 반드시 확인하세요.',
  },
};

export const MATERIAL_ORDER = ['PLA', 'PLA+', 'PETG', 'ABS', 'ASA', 'TPU', 'Nylon', 'PC'];
